In [153]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits

from sklearn.model_selection import train_test_split

In [154]:
digits = load_digits()

In [155]:
x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [156]:
lr = LogisticRegression(solver='lbfgs',  multi_class='auto', max_iter=10000)
lr.fit(x_train, y_train)
lr.score(x_test, y_test)

0.9648148148148148

In [157]:
svm = SVC(gamma='auto') 
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

0.34629629629629627

In [158]:
rf = RandomForestClassifier(n_estimators=100)
rf.fit(x_train, y_train)
rf.score(x_test, y_test)

0.9611111111111111

In [159]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [160]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [161]:
def get_score(model, x_train, x_test, y_train, y_test):
    model.fit(x_train, y_train)
    return model.score(x_test, y_test)

In [162]:
get_score(LogisticRegression(solver='lbfgs',  multi_class='auto', max_iter=10000), x_train, x_test, y_train, y_test)

0.9648148148148148

In [163]:
 get_score(SVC(gamma='auto'), x_train, x_test, y_train, y_test)

0.34629629629629627

**StratifiedKFold** is similar to KFold but it is little better in a way that when 
you are separating out your folds it will devide each of the classification categories in a uniform way

In [164]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)   ## kf = KFold(n_splits=3)

In [165]:
scores_lr = []
scores_svm = []
scores_rf = []

##scores_rf.append

In [166]:


# r train_index, test_index in kf.split(digits.data):
#   x_train, x_test, y_train, y_test = digits.data[train_index], digits.data[test_index],\
#                                        digits.target[train_index], digits.target[test_index]
#   
#   print(get_score(LogisticRegression(solver='lbfgs', multi_class='auto', max_iter=10000), x_train, x_test, y_train, y_test))
#   print(get_score(SVC(gamma='auto'), x_train, x_test, y_train, y_test))  
#   print(get_score(RandomForestClassifier(n_estimators=100), x_train, x_test, y_train, y_test))    
#   

In [167]:
for train_index, test_index in kf.split(digits.data):
    x_train, x_test, y_train, y_test = digits.data[train_index], digits.data[test_index],\
                                         digits.target[train_index], digits.target[test_index] 
    scores_lr_value=(get_score(LogisticRegression(solver='lbfgs', multi_class='auto', max_iter=10000), x_train, x_test, y_train, y_test))
    scores_svm_value=(get_score(SVC(gamma='auto'), x_train, x_test, y_train, y_test))  
    scores_rf_value=(get_score(RandomForestClassifier(n_estimators=100), x_train, x_test, y_train, y_test))    
    ##print("\n")
    ##print(scores_lr_value)
    scores_lr.append(scores_lr_value)
    scores_svm.append(scores_svm_value)
    scores_rf.append(scores_rf_value)

In [168]:
scores_lr

[0.9282136894824707, 0.9415692821368948, 0.9165275459098498]

In [169]:
scores_svm

[0.41068447412353926, 0.41569282136894825, 0.4273789649415693]

In [170]:
scores_rf

[0.9332220367278798, 0.9482470784641068, 0.9181969949916527]

In [171]:
from sklearn.model_selection import cross_val_score

In [177]:
cross_val_score(LogisticRegression(solver='lbfgs', multi_class='auto', max_iter=10000), digits.data, digits.target, cv=5)

array([0.92582418, 0.87845304, 0.94150418, 0.93557423, 0.90140845])

In [180]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target, cv=5)

array([0.43406593, 0.40883978, 0.41504178, 0.48739496, 0.49859155])

In [185]:
cross_val_score(RandomForestClassifier(n_estimators=80), digits.data, digits.target, cv=5)

array([0.93406593, 0.9198895 , 0.95543175, 0.96638655, 0.93521127])